apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gatus.fullname" . }}
  namespace: {{ template "gatus.namespace" . }}
  labels:
    {{- include "gatus.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
