{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "gatus.fullname" . }}
  namespace: {{ template "gatus.namespace" . }}
  labels:
    {{- include "gatus.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
    {{- include "gatus.selectorLabels" . | nindent 6 }}
  {{- if .Values.networkPolicy.ingress.selectors }}
  ingress:
    - from:
      {{-  toYaml .Values.networkPolicy.ingress.selectors | nindent 6 }}
    - ports:
      - port: {{ .Values.service.targetPort }}
  {{- end }}
{{- end }}
