on:
  push:
    branches:
      - main
    paths:
      - README.md
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@v3
        with: { ref: gh-pages }
      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          git add README.md
          git commit --signoff -m "Sync README.md from main"
          git push
