name: Sync README.md into gh-pages branch
permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  sync:
    permissions:
      contents: write # to make git push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cp -f README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@v4
        with: { ref: gh-pages }
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README.md from main"
          git push
