name: Test Workflow
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup helm
      uses: azure/setup-helm@v1
      with: { version: v3.7.2 }
    - name: Lint
      run: make lint
